### ISSUE TITLE
c64 dram test mega2560

### ISSUE THREAD

**Issue by toms001** [jamarju/c64_test_tools#2]
Hi,
just uploaded the c64 dram test to a ordinary mega2560 without any wires.
The test PASSes every time without an attached dram. How is this possible?
Regards,
Thomas

**Comment by jamarju** [comment]
The mega2560 version of the RAM test outputs pass/fail on the serial output, unlike the 328p version, which uses the LED.

**Comment by toms001** [comment]
That is not what i meant... if you have a mega2560 with nothing connected, it always says PASS.
I expected a different result with _no_ 64k x 4 connected

**Comment by jamarju** [comment]
Ok, ok sorry, I see what you mean. Let me figure out what's going on here.

**Comment by jamarju** [comment]
If you have a known working RAM chip wired up, could you please try the following change in line 118 of `w()`?

Replace this:
```
    PORTF &= 0b11110000;                              // ... no pull-ups
```

with this:
```
    PORTF |= 0b00001111;                              // keep pull-ups
```

Apparently written data gets latched by the pin circuitry or stored up in some small capacitance somehow. When nothing is connected, pulling up the inputs before reading should pass the '1111' test and fail the others.
