### ISSUE TITLE
PLA Test

### ISSUE THREAD

**Issue by rj45jack** [jamarju/c64_test_tools#3]
I'm trying to run the PLA test using my Uno and have an issue with the diagram provided.

What exactly does this mean:
 **PLA F0/4 --- C2  
 PLA F1/5 --- C3  
 PLA F2/6 --- C4  
 PLA F2/7 --- C5**

What is the F2/6, F2/7 and others exactly mean?

Thanks,

**Comment by jamarju** [comment]
You have to test output nybbles separately because of the lack of pins on the Uno. Find this line in the code:

```
#define TEST_NIBBLE 0   // 0 to test low nibble (outputs F0-3), 1 to test high nibble (outputs F4-7)
```

Then test PLA's F0-F3 wired to Uno's A2-A5.

Next, change the above line to:

```
#define TEST_NIBBLE 1   // 0 to test low nibble (outputs F0-3), 1 to test high nibble (outputs F4-7)
```

Then test PLA's F4-F7 wired to Uno's A2-A5.

**Comment by rj45jack** [comment]
Much more clear. Thank you!
