### ISSUE TITLE
Test says fail PLA but in another C64 the chip works normally

### ISSUE THREAD

**Issue by leonpierre** [jamarju/c64_test_tools#4]
I flashed your PLA test program to an Arduino Uno and wired it to the PLA (8700-001) as declared and figured out that with a working PLA (Fujitsu 251064-01) everything looks OK but with the mentioned MOS 8700-001 I got LED flashes -> FAILED.

So if I put the "failed" 8700-001 to a working C64 everything is good! I have a video of the setup here: https://www.youtube.com/watch?v=KTHi8Ji6yds

Btw. any idea what could be wrong with this image after boot: https://imgur.com/a/6CjX6wW

Thank you.

**Comment by jamarju** [comment]
You are getting two errors (1 flash + 3 flashes), so the faulty pins are F0 and F2. Can you double check the wiring especially on those two pins? Does the high half (F4...F7) also show errors?

No idea about your boot image, but looks like RAM to me according to the pictorial guide: https://derbian.webs.com/c64diag/index.htm

**Comment by leonpierre** [comment]
I wired it according to your PLA Test draft. 

One question: 
PLA F2/6 --- C4  | [ ]A4/SDA
PLA F2/7 --- C5  | [ ]A5/SCL

is this by intention to wire F2 to A4 and A5? Because I did it like

PLA F2/6 --- C4  | [ ]A4/SDA
PLA F3/7 --- C5  | [ ]A5/SCL <==== F3 not F2

**Comment by jamarju** [comment]
Yes, that was a typo. You're right, Arduino A5 should go to PLA F3.

As for your original problem, try adding a couple more nops in the peek function. Ie: instead of this:

```
  asm("nop"); // 62.5 ns
  asm("nop"); // 62.5 ns
```

Do this:

```
  asm("nop"); // 62.5 ns
  asm("nop"); // 62.5 ns
  asm("nop"); // 62.5 ns
  asm("nop"); // 62.5 ns
```

That will give twice as much time for the PLA to propagate the signals.

**Comment by leonpierre** [comment]
I did your changes and tested it again with equal results. Here is a video of the same setup but with Fujitsu 251064-01 instead of MOS 8700-001 PLA:

https://www.youtube.com/watch?v=bH1ezJzycxE

It's weird for me that both PLA IC's are working in a real C64 but not with your PLA test. Any suggestions what could be wrong?

Thank you!

**Comment by jamarju** [comment]
Did you connect /CE to GND? It's hard to tell in your video but it seems to me that you left it floating.

**Comment by leonpierre** [comment]
Nope, but if I connect /CE to GND I have permanent LED flashes.

**Comment by jamarju** [comment]
Can you record another video of the permanent flashes while /CE is connected to GND?

**Comment by leonpierre** [comment]
Voila: https://youtu.be/ocNNEUnGQsc

**Comment by jamarju** [comment]
That chip is PASSING the test.

A failure is indicated by a 1 second pause followed by flashing a number of times depending on the erroring pin, followed by another 1 second pause.
